{
  "contributors": "None",
  "truncated": "False",
  "text": "I want the blue iPhone",
  "in_reply_to_status_id": "None",
  "id": "398906307396505600L",
  "favorite_count": "0",
  "source": "<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>",
  "retweeted": "False",
  "coordinates": "None",
  "entities": {
    "symbols": [],
    "user_mentions": [],
    "hashtags": [],
    "urls": []
  },
  "in_reply_to_screen_name": "None",
  "id_str": "398906307396505600",
  "retweet_count": "0",
  "in_reply_to_user_id": "None",
  "favorited": "False",
  "user": {
    "follow_request_sent": "None",
    "profile_use_background_image": "True",
    "default_profile_image": "False",
    "id": "1902595495",
    "verified": "False",
    "profile_image_url_https": "https://pbs.twimg.com/profile_images/378800000710062990/451c16c72a6dffd1b958d76eeb0757df_normal.jpeg",
    "profile_sidebar_fill_color": "DDEEF6",
    "profile_text_color": "333333",
    "followers_count": "49",
    "profile_sidebar_border_color": "C0DEED",
    "id_str": "1902595495",
    "profile_background_color": "C0DEED",
    "listed_count": "0",
    "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
    "utc_offset": "None",
    "statuses_count": "338",
    "description": "This is not what I signed up for",
    "friends_count": "54",
    "location": "",
    "profile_link_color": "0084B4",
    "profile_image_url": "http://pbs.twimg.com/profile_images/378800000710062990/451c16c72a6dffd1b958d76eeb0757df_normal.jpeg",
    "following": "None",
    "geo_enabled": "True",
    "profile_banner_url": "https://pbs.twimg.com/profile_banners/1902595495/1383891015",
    "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
    "name": "Mercy Dominguez",
    "lang": "en",
    "profile_background_tile": "False",
    "favourites_count": "23",
    "screen_name": "raysofmercyyy",
    "notifications": "None",
    "url": "None",
    "created_at": "Wed Sep 25 02:29:42 +0000 2013",
    "contributors_enabled": "False",
    "time_zone": "None",
    "protected": "False",
    "default_profile": "True",
    "is_translator": "False"
  },
  "geo": "None",
  "in_reply_to_user_id_str": "None",
  "lang": "en",
  "created_at": "Fri Nov 08 20:14:09 +0000 2013",
  "filter_level": "medium",
  "in_reply_to_status_id_str": "None",
  "place": "None"
}